apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinit-restart
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: infinit
        image: hhovsepy/exit1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: infinit
  labels:
    name: infinit
    service: infinit
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
